package scatnp_gui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import scatnp_Dao.UserDao;
import scatnp_pojo.CurrentUser;
import scatnp_pojo.UserPojo;



/**
 *
 * @author LENOVO
 */
public class loginframe extends javax.swing.JFrame {

    /**
     * Creates new form loginframe
     */
    public loginframe() {
        initComponents();
        Color c=new Color(0,0,0,1);
      txtUserId.setBackground(c);
      txtPwd.setBackground(c);
      
      
        this.setLocationRelativeTo(null);
    }
public boolean validateInputs(String userId,String password)
        {
            if(userId.isEmpty()||password.isEmpty())
                return false;
            return true;
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        LoginPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        rbAdmin = new javax.swing.JRadioButton();
        rbHr = new javax.swing.JRadioButton();
        rbStudent = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        btnSignUp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPwd = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\OneDrive\\Desktop\\images\\pngs\\homePage.jpg")); // NOI18N
        LoginPanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 630, 390));

        txtUserId.setBackground(new java.awt.Color(120, 120, 120));
        txtUserId.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        txtUserId.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtUserId.setOpaque(false);
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });
        LoginPanel.add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 310, 30));

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel3.setText("Email or UserId");
        LoginPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 113, 216, -1));

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel4.setText("Password");
        LoginPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 248, 224, 43));
        LoginPanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 481, 500, 10));

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setText("Select User Type:");
        LoginPanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 509, 177, 41));

        buttonGroup1.add(rbAdmin);
        rbAdmin.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        rbAdmin.setText("Admin");
        LoginPanel.add(rbAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 559, 118, -1));

        buttonGroup1.add(rbHr);
        rbHr.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        rbHr.setText("Company Hr");
        rbHr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHrActionPerformed(evt);
            }
        });
        LoginPanel.add(rbHr, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 559, -1, -1));

        buttonGroup1.add(rbStudent);
        rbStudent.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        rbStudent.setText("Student");
        LoginPanel.add(rbStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(442, 559, -1, -1));

        btnLogin.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnLogin.setText("Log In");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        LoginPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 612, 240, 42));

        btnSignUp.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        LoginPanel.add(btnSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 612, 193, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\OneDrive\\Desktop\\images\\pngs\\hrimages\\transparent logo.png")); // NOI18N
        LoginPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 223, 82));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\OneDrive\\Desktop\\images\\pngs\\TextFieldPic.png")); // NOI18N
        LoginPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 340, 70));

        txtPwd.setBackground(new java.awt.Color(120, 120, 120));
        txtPwd.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtPwd.setOpaque(false);
        txtPwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPwdActionPerformed(evt);
            }
        });
        LoginPanel.add(txtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 320, 40));

        jLabel8.setBackground(new java.awt.Color(120, 120, 120));
        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\OneDrive\\Desktop\\images\\pngs\\hrimages\\TextFieldPic.png")); // NOI18N
        LoginPanel.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 360, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\LENOVO\\OneDrive\\Desktop\\images\\pngs\\hrimages\\login.jpg")); // NOI18N
        LoginPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1060, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LoginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String type;
        if(rbAdmin.isSelected())
            type="Admin";
        else if(rbHr.isSelected())
            type="Hr";
        else if(rbStudent.isSelected())
            type="Student";
        else
        {
            JOptionPane.showMessageDialog(null,"Please Select the Type First","User Type Not Selected",JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        String userId=txtUserId.getText().toUpperCase();
        String pwd=txtPwd.getText();
        if(validateInputs(userId,pwd))
        {
         UserPojo user=new UserPojo();
         user.setUserid(userId);
         user.setPassword(pwd);
         user.setType(type);
         try
         {
            boolean res= UserDao.validateUser(user);
            
            if(res==true)
            {
                if(CurrentUser.getType().equals("Admin"))
                {
                    JOptionPane.showMessageDialog(null,"Welcome Admin:"+CurrentUser.getName(),"Welcome",JOptionPane.INFORMATION_MESSAGE);
                
               adminOptionFrame admin=new adminOptionFrame();
               
               admin.setVisible(true);
               this.dispose();
              
                }
                else if(CurrentUser.getType().equals("Hr"))
                {
                    JOptionPane.showMessageDialog(null,"Welcome Hr::"+CurrentUser.getName(),"Welcome",JOptionPane.INFORMATION_MESSAGE);
             new    HrOptionsFrame().setVisible(true);
             
            this.dispose();
                }
                
            }
            else
            {
                JOptionPane.showMessageDialog(null,"UserId/Password is not Correct ","Invalid Inputs",JOptionPane.INFORMATION_MESSAGE);
                buttonGroup1.clearSelection();
                
                return;
            }
         }
         catch(SQLException sq)
         {
           JOptionPane.showMessageDialog(null,"Databse Error ","DB ERROR ",JOptionPane.ERROR_MESSAGE);
           sq.printStackTrace();
           
         }
               
            
        }
        else
        {
              JOptionPane.showMessageDialog(null,"Please Fill userid/pwd ","Blank Inputs",JOptionPane.INFORMATION_MESSAGE);
            return;
          
        }
   
       
            
            
           
        
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void rbHrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHrActionPerformed

    private void txtPwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPwdActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbAdmin;
    private javax.swing.JRadioButton rbHr;
    private javax.swing.JRadioButton rbStudent;
    private javax.swing.JPasswordField txtPwd;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
